name: Lint

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run actionlint
        id: actionlint
        uses: srizzo/actionlint@adjustments
        with:
          fail-on-error: false
#      - name: Install Taskmates
#        uses: taskmates/install-taskmates@v1
#        with:
#          version: main
      - name: Set up Taskmates
        run: |
          export TASKMATES_HOME=${{ runner.temp }}/.taskmates
          echo TASKMATES_HOME=$TASKMATES_HOME >> $GITHUB_ENV
          

#      - name: Display actionlint results
#        if: ${{ steps.actionlint.outputs.exit-code != 0 }}
#        run: |
#          echo "Actionlint found the following issues:"
#          echo "$ACTIONLINT_STDOUT"
#        env:
#          ACTIONLINT_STDOUT: ${{ steps.actionlint.outputs.stdout }}

      - name: Compose Chat
        run: |
          export MARKDOWN_CHAT_PATH=${{ runner.temp }}/chat.md
          echo MARKDOWN_CHAT_PATH=$MARKDOWN_CHAT_PATH >> $GITHUB_ENV
          
          cat <<EOF >> "$MARKDOWN_CHAT_PATH"
          Please fix the following linting issues: 
          
          "$ACTIONLINT_STDOUT"
          EOF
          
          cat "$MARKDOWN_CHAT_PATH"
        env:
          ACTIONLINT_STDOUT: ${{ steps.actionlint.outputs.stdout }}

