name: Lint

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run actionlint
        id: actionlint
        uses: raven-actions/actionlint@v2
        with:
          fail-on-error: false
#      - name: Install Taskmates
#        uses: taskmates/install-taskmates@v1
#        with:
#          version: main
#      - name: Set up Taskmates
#        run: |
#          export TASKMATES_HOME=${{ runner.temp }}/.taskmates
#          echo TASKMATES_HOME=$TASKMATES_HOME >> $GITHUB_ENV
      - name: Display actionlint results
        if: ${{ steps.actionlint.outputs.exit-code != 0 }}
        run: |
          echo "Actionlint found the following issues:"
          echo "${{ steps.actionlint.outputs.stdout }}"
