name: Lint

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      GH_TOKEN: ${{ secrets.ACTIONLINT_POC_GITHUB_TOKEN }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Run actionlint
        id: actionlint
        uses: srizzo/actionlint@adjustments
        with:
          fail-on-error: false
      - name: Stop Github markers
        if: steps.actionlint.outputs.exit-code != 0
        run: |
          stopMarker=$(uuidgen)
          echo "::stop-commands::$stopMarker"
      - name: Install Taskmates
        if: steps.actionlint.outputs.exit-code != 0
        uses: taskmates/install-taskmates@v1
        with:
          version: main
      - name: Set up Taskmates
        if: steps.actionlint.outputs.exit-code != 0
        run: |
          export TASKMATES_HOME=${{ runner.temp }}/.taskmates
          echo TASKMATES_HOME=$TASKMATES_HOME >> $GITHUB_ENV
          
          mkdir -p "$TASKMATES_HOME/private"
          cat <<EOF >> "$TASKMATES_HOME/private/linting_fixer.md"
          ---
          tools:
            read_file:
              allow: ".github/workflows/*"
            write_file:
              allow: ".github/workflows/*"
          ---
          
          You're a helpful AI Agent that fixes linting issues.
          
          Read the full content of each affected file before making any changes.
          
          Only fix the linting issues mentioned in the chat. Do not make any other changes.
          
          Skip any issues that you're not sure how to fix. 
          
          EOF

      - name: Compose Chat
        if: steps.actionlint.outputs.exit-code != 0
        run: |
          export MARKDOWN_CHAT_PATH=${{ runner.temp }}/chat.md
          echo MARKDOWN_CHAT_PATH=$MARKDOWN_CHAT_PATH >> $GITHUB_ENV
          
          cat <<EOF >> "$MARKDOWN_CHAT_PATH"
          Hey @linting_fixer, please fix the following issues: 
          
          "$ACTIONLINT_STDOUT"
          EOF
          
          cat "$MARKDOWN_CHAT_PATH"
        env:
          ACTIONLINT_STDOUT: ${{ steps.actionlint.outputs.stdout }}

      - name: Run Taskmates
        id: run_taskmates
        if: steps.actionlint.outputs.exit-code != 0
        run: |
          set -Eeuo pipefail
          
          echo Running Taskmates...
          
          cat "$MARKDOWN_CHAT_PATH" | taskmates complete \
              --model=gpt-4o \
              --max-steps=20 \
              --format full | tee "$RUNNER_TEMP/response.md"

          cp "$RUNNER_TEMP/response.md" "$MARKDOWN_CHAT_PATH"

      - name: Create PR
        if: steps.actionlint.outputs.exit-code != 0 && steps.run_taskmates.conclusion == 'success'
        env:
          GH_TOKEN: ${{ secrets.ACTIONLINT_POC_GITHUB_TOKEN }}
        run: |
          set -Eeuo pipefail 
          
          # Check for uncommitted changes in workflows
          if [[ -n $(git status --porcelain .github/workflows) ]]; then
            # Set branch name, PR title, and PR body
            BRANCH_NAME="fix-workflow-linting"
            PR_TITLE="Fix workflow linting issues"
            PR_BODY="This PR addresses linting issues in the GitHub Actions workflows."
          
            # Configure git
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
          
            # Set up authentication for git operations
            git config --global url."https://${GH_TOKEN}@github.com/".insteadOf "https://github.com/"
          
            # Check if branch exists
            if git ls-remote --exit-code --heads origin $BRANCH_NAME; then
              # Branch exists, switch to it
              git fetch origin $BRANCH_NAME
              git checkout $BRANCH_NAME
            else
              # Branch doesn't exist, create it
              git checkout -b $BRANCH_NAME
            fi
          
            # Add changes and commit
            git add .github/workflows
            git commit -m "Fix workflow linting issues"
          
            # Push the branch
            git push origin $BRANCH_NAME
          
            # Check if PR already exists
            if ! gh pr list --head $BRANCH_NAME --json number | grep -q '"number":'; then
              # Create the PR if it doesn't exist
              gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base main --head $BRANCH_NAME
            else
              echo "PR already exists. Skipping PR creation."
            fi
          else
            echo "No changes to workflows. Skipping PR creation."
          fi
