name: Lint

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Run actionlint
        id: actionlint
        uses: srizzo/actionlint@adjustments
        with:
          fail-on-error: false
      - name: Install Taskmates
        if: steps.actionlint.outputs.exit-code != 0
        uses: taskmates/install-taskmates@v1
        with:
          version: main
      - name: Set up Taskmates
        if: steps.actionlint.outputs.exit-code != 0
        run: |
          export TASKMATES_HOME=${{ runner.temp }}/.taskmates
          echo TASKMATES_HOME=$TASKMATES_HOME >> $GITHUB_ENV
          
          mkdir -p "$TASKMATES_HOME/private"
          cat <<EOF >> "$TASKMATES_HOME/private/linting_fixer.md"
          ---
          tools:
            read_file:
              allow: ".github/workflows/*"
            write_file:
              allow: ".github/workflows/*"
          ---
          
          You're a helpful AI Agent that fixes linting issues.
          
          Read the full content of each affected file before making any changes.
          
          Only fix the linting issues mentioned in the chat. Do not make any other changes.
          
          Skip any issues that you're not sure how to fix. 
          
          EOF

      - name: Compose Chat
        if: steps.actionlint.outputs.exit-code != 0
        run: |
          export MARKDOWN_CHAT_PATH=${{ runner.temp }}/chat.md
          echo MARKDOWN_CHAT_PATH=$MARKDOWN_CHAT_PATH >> $GITHUB_ENV
          
          cat <<EOF >> "$MARKDOWN_CHAT_PATH"
          Hey @linting_fixer, please fix the following issues: 
          
          "$ACTIONLINT_STDOUT"
          EOF
          
          cat "$MARKDOWN_CHAT_PATH"
        env:
          ACTIONLINT_STDOUT: ${{ steps.actionlint.outputs.stdout }}

      - name: Run Taskmates
        id: run_taskmates
        if: steps.actionlint.outputs.exit-code != 0
        run: |
          set -Eeuo pipefail
          
          echo Running Taskmates...
          
          cat "$MARKDOWN_CHAT_PATH" | taskmates complete \
              --model=gpt-4o \
              --max-steps=20 \
              --format full | tee "$RUNNER_TEMP/response.md"

          cp "$RUNNER_TEMP/response.md" "$MARKDOWN_CHAT_PATH"

      - name: Create PR
        if: steps.actionlint.outputs.exit-code != 0
        run: |
          set -Eeuo pipefail 

          taskmates complete --model claude-3-haiku-20240307 --format completion "@guard report true if source code has been modified" <"$MARKDOWN_CHAT_PATH" |
          tee "$RUNNER_TEMP/guard-pr.md" &&
          taskmates complete --format full "Hey @gh please create a feature branch, commit the modified files, and open a PR" <"$MARKDOWN_CHAT_PATH" |
          tee "$RUNNER_TEMP/create-pr.md"
          
          cp "$RUNNER_TEMP/create-pr.md" "$MARKDOWN_CHAT_PATH"
